export const isViewLive = {
  mainTable: true,
  kanban: true,
  list: false,
  calendar: false,
  timeline: false,
  workload: false,
  time: false,
  recurring: false,
  completed: false,
  sop: false,
  doc: false,
  updates: false,
  dashboard: false,
};